name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: pwd && mkdir -p /Users/runner/go/src/ && ln -s /Users/runner/work/MIDIRouter/MIDIRouter /Users/runner/go/src/ && go get github.com/youpy/go-coremidi && go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Push Binary
      uses: actions/upload-artifact@v2
          with:
            name: midi-router
            path: cmd/midirouter/midirouter