name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: ln -s /home/runner/work/MIDIRouter/MIDIRouter /home/runner/go/src/ && go build -v ./...

    - name: Test
      run: go test -v ./...
